# Generated by Django 4.0.10 on 2023-09-23 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания записи')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновления записи')),
                ('name', models.CharField(max_length=255, verbose_name='Название урока')),
                ('video', models.URLField(verbose_name='Видео урока')),
                ('duration', models.IntegerField(verbose_name='Продолжительность')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
